sudo: required

language: bash

services:
  - docker

install:
  - docker-compose -v
  - docker-compose build
  - docker-compose run --rm app

script:
  - docker pull quay.io/keboola/developer-portal-cli-v2:latest
  - export REPOSITORY=`docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD
    quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository
    keboola keboola.ex-db-pgsql`
  - docker tag keboola/ex-db-pgsql:latest $REPOSITORY:master
  - eval $(docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD
    quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login
    keboola keboola.ex-db-pgsql)
  - docker push $REPOSITORY:master
  - docker pull quay.io/keboola/syrup-cli:latest
  - docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job keboola.ex-db-pgsql
    285843250 master
  - docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job keboola.ex-db-pgsql
    287599200 master

after_success:
  - docker images

after_error:
  - docker-compose logs

after_failure:
  - docker-compose logs

deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    tags: true

notifications:
  email: false
  slack:
    secure: WQECTq6ttDt8XrxffH0P9zcCTCY1wDWgXmUjmx4SjG24LV+2Of2QZ0uuiqfGEMgB88pzvTjy/LXxTXZSX0eNZ+ZtjsHLndNULbvDu9VXgalQSc+PsY8dYny4+98Vee2TJkSIaT0IYjjSqP7gMssi+mOyCpg8FQvFCHRMMd8k9Z2GQeJ8zP3m6ab6c/H777uOa6uPERWWi03eVQg/w+0ylciYr/RCy90sxpMog5gvkQLuDZ9CQixdIdU6ohqLYywhy/1ldYk14pjoapDwa0ITQtruvidETuPD+JM+qKIQLROEfKYLNdBxnEfRilJQL2+EtJdZck0xynwkHjrB9zlJGgcImtIaSD0aB5bgLysT0F5jBbOuUIv/j+9p7sIDQjyDS/tHrvxapR7ZAZOn6xH//4U+RLVFrF0hIaRrC5YLNx1jQGcQF9k67Cj6VudtZRQxEQDTBMOwdTFHerER9EWSQ1szQ7J8iJoEOVQuZmefHl99YCkPkDZcjirBdtLAkg6cGXVTin/8AYYcvqRIA/GrGHeEDifZSucy8ZhL9iXPntyz8VAxawvijTjgctbMt+31nUEAKNGBJgzL5X3dyq7/iFdCBiSdZaeTn2eK4xPM8wFMrCHXa+BOBRrM62C0C0NCstnYjgUn6bdLUQaqR0diJ1bfcfoIpwaAVFjbk1InIrY=
